### ISSUE TITLE
Simplifiy @CommandOptions by removing permission specifications

### ISSUE THREAD

**Issue by Snabeldier** [MineValley/Core-API#133]
Most of the permission requirements are used very rarely. There is the option to rule the command access precisely in the isPermissioned() method. Using the isPermissioned() method seems better to keep the code short and readable.

**Comment by Lapotor** [comment]
What are the disadvantages of the proposed solution

**Comment by Snabeldier** [comment]
The solution that is mentioned here in this issue has no disadvantages, but the work that has to be done to implement it.

The way permissions are handled at the moment works fine and is easy to use. But it uses kind of a redundant permission check, since the universal permission check came later and made it's predecessor obsolete. The old permission check used to have some unintuitive peculiarities that sometimes caused unintentioned code behaviour.

The idea of this issue is to get rid of the obsolete and redundant permission check and to fully migrate into the new one and removing the old one
