### ISSUE TITLE
add own triconsumer to replace log4j 

### ISSUE THREAD

**Issue by Snabeldier** [MineValley/Core-API#147]
log4j is only added as dependency to have access to the TriConsumer class. Let's create our own one

**Comment by Lapotor** [comment]
Why?
What are the benefits of the own implementation?

**Comment by Snabeldier** [comment]
since the triconsumer is a tiny fragment of log4j it's barely necessary to implement the whole lib. Reducing the amount of dependencies reduces code complexity and prevents vulnerabilities

**Comment by Snabeldier** [comment]
It's also pretty safe to say, that the usage of TriConsumer as we do at the moment isn't even really necessary and an be replaced by a common BiConsumer
