### ISSUE TITLE
Suggestion to use dependabot or renovatebot

### ISSUE THREAD

**Issue by Lapotor** [MineValley/Core-API#18]
## Description
This is a suggestion to use dependabot or renovatebot on the Core-API repository. These tools can help automate the process of updating dependencies and keep the project up-to-date with the latest security patches and bug fixes.

## Benefits
- Saves time and effort by automating dependency updates.
- Keeps the project up-to-date with the latest security patches and bug fixes.
- Helps maintain a healthy and secure codebase.

## Proposed Solution
It is proposed that dependabot or renovatebot be used to manage dependencies on this repository. Both tools are widely used and have proven to be effective in keeping projects up-to-date with the latest dependencies.

### Additional Information
- [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates)
- [Renovatebot](https://github.com/renovatebot/renovate)

**Comment by Snabeldier** [comment]
Thank you!
I will take a look at it :)

**Comment by Snabeldier** [comment]
I think it's a good idea to use RenovateBot since I've already had some experience with it

Are there any missing features in RenovateBot that Dependabot provides?

**Comment by Lapotor** [comment]
Renovate and Dependabot do work well together when it comes to security patches.

Renovate and Dependabot are almost the same.
The biggest differences are that Renovate updates are more crowd sourced and Dependabot is directly integrated into GitHub.

So for the most part they are the same.

---

Personally I like Renovate more because it is more configurable than Dependabot.

**Comment by Snabeldier** [comment]
since we are purposely using an outdated version of minecraft, there will be updates that we will have to ignore as they aren't compatible with our version. This, and the fact that we don't use many depedencies at all, means that dependabot/renovatebot has little to none use for us.

Thank you anyways for your help!
