### ISSUE TITLE
[Docs] Missing `@param` Tag for `Task.setRecipeName()` Method

### ISSUE THREAD

**Issue by Lapotor** [MineValley/Core-API#38]
https://github.com/MineValley/Core-API/blob/d873f5bf52f61b4bfd265c5f20dd29c84beecfde/src/main/java/minevalley/core/api/corporations/Task.java#L16-L19

The absence of the `@param` tag for the `name` parameter for the `setRecipeName()` method of the `Task` class is causing a significant issue. This omission is breaking the JavaDoc generation process during the build.

To resolve this issue, update the JavaDoc for the `setRecipeName()` method by including the necessary `@param` tag for the `name` parameter. This will not only fix the JavaDoc generation problem but also ensure that developers have essential information about the method's parameters.

**Comment by Snabeldier** [comment]
Falscher Methodenname :)
